export const FETCH_VIDEO_GAMES_SUCCESS = "FETCH_VIDEO_GAMES_SUCCESS";
export const FETCH_VIDEO_GAMES_FAILURE = "FETCH_VIDEO_GAMES_FAILURE";
export const FILTER_BY_GENRE = "FILTER_BY_GENRE";
export const ORDER_BY = "ORDER_BY";
export const PAGINATE = "PAGINATE";
