export const FETCH_VIDEO_GAMES_SUCCESS = "FETCH_VIDEO_GAMES_SUCCESS";
export const FETCH_VIDEO_GAMES_FAILURE = "FETCH_VIDEO_GAMES_FAILURE";

export const FETCH_GAME_DETAILS_SUCCESS = "FETCH_GAME_DETAILS_SUCCESS";
export const FETCH_GAME_DETAILS_FAILURE = "FETCH_GAME_DETAILS_FAILURE";

export const FETCH_GENRES_SUCCESS = "FETCH_GENRES_SUCCESS";
export const FETCH_GENRES_FAILURE = "FETCH_GENRES_FAILURE";

export const CREATE_VIDEO_GAME_SUCCESS = "CREATE_VIDEO_GAME_SUCCESS";
export const CREATE_VIDEO_GAME_FAILURE = "CREATE_VIDEO_GAME_FAILURE";

export const SORT_VIDEO_GAMES_BY_NAME = "SORT_VIDEO_GAMES_BY_NAME";
export const SORT_VIDEO_GAMES_BY_RATING = "SORT_VIDEO_GAMES_BY_RATING";

export const FILTER_VIDEO_GAMES_BY_GENRE = "FILTER_VIDEO_GAMES_BY_GENRE";

export const FILTER_VIDEO_GAMES_BY_ORIGIN = "FILTER_VIDEO_GAMES_BY_ORIGIN";

export const PAGINATE = "PAGINATE";
