export const FETCH_VIDEO_GAMES_SUCCESS = "FETCH_VIDEO_GAMES_SUCCESS";
export const FETCH_VIDEO_GAMES_FAILURE = "FETCH_VIDEO_GAMES_FAILURE";
export const FETCH_GAME_DETAILS_REQUEST = "FETCH_GAME_DETAILS_REQUEST";
export const FETCH_GAME_DETAILS_SUCCESS = "FETCH_GAME_DETAILS_SUCCESS";
export const FETCH_GAME_DETAILS_FAILURE = "FETCH_GAME_DETAILS_FAILURE";
export const FILTER_BY_GENRE = "FILTER_BY_GENRE";
export const ORDER_BY = "ORDER_BY";
export const PAGINATE = "PAGINATE";
